version: "3.9"
services:
  emt-bus-api:
    build: .
    container_name: emt-bus-api
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
