name = "emt-valencia-bus-api"
main = "src/index.js"
compatibility_date = "2025-10-28"
compatibility_flags = ["nodejs_compat"]

# Limits - adjust based on your Cloudflare plan
# Free plan: 10ms CPU time, Paid: 30s CPU time
# These are configured automatically based on your account
# [limits]
# cpu_ms = 10  # CPU time limit in milliseconds (Free tier)

# Environment variables
[vars]
GTFS_URL = "https://opendata.vlci.valencia.es/dataset/google-transit-lines-stops-bus-schedules/resource/c81b69e6-c082-44dc-acc6-66fc417b4e66/download/google_transit.zip"
TZ = "Europe/Madrid"

# KV namespace for caching GTFS data (RECOMMENDED for free tier!)
# This dramatically reduces CPU time and improves response times
# 
# Setup instructions:
# 1. Create KV namespace:
#    wrangler kv:namespace create "GTFS_CACHE"
#
# 2. For preview/dev:
#    wrangler kv:namespace create "GTFS_CACHE" --preview
#
# 3. Copy the IDs from output and uncomment below:
#
[[kv_namespaces]]
binding = "GTFS_CACHE"
preview_id = "fe1c9f9870a5437e868404721cddc642"
#
# Free tier limits:
# - 100,000 reads/day
# - 1,000 writes/day
# - 1GB storage
# This is more than enough for caching routes, stops, and trips!
